### ISSUE TITLE
A quite unavoidable damage

### ISSUE THREAD

**Issue by Birdie0** [Zamiell/jud6s#4]
http://www.twitch.tv/birdie0/v/50034184?t=59m40s
![2016-02-24-2157-13 flv_snapshot_00 59 46_ 2016 02 24_23 50 35](https://cloud.githubusercontent.com/assets/7945905/13302212/6de909e0-db51-11e5-999c-bedcbdee4d0f.jpg)

**Comment by Zamiell** [comment]
LOL, damn

**Comment by Hyphen-ated** [comment]
this doesn't look unavoidable to me. you could have walked down so the fly wouldn't hit you

**Comment by Zamiell** [comment]
I tested this today on stream with the same seed, and Hyphen's intuition was correction - you can move down to dodge. It's a hard room, but not necessarily unavoidable damage.
