### ISSUE TITLE
Shortening animations for certain fullscreen actions

### ISSUE THREAD

**Issue by ghost** [Zamiell/jud6s#8]
Hi, not sure whether this plays into gameplay decisions or not, but I am a big fan of how clean and fast boss animations and other slow transitions are cut in this mod.

My main annoyance is that this highlights other slow animations in the game, notably giantbook animations for certain cards, runes, books and black hearts.

I think that there's enough speed difference that while racing you might avoid say dry baby as he has a tendency to pause the game, sometimes for no benefit, but for the most part I would expect it just cleans up pointless slownesses (you're not going to choose to not use book of revelation or jera just because of the animation.

An example of a mod (WARNING: UNLICENSED CODE) which does this is below.

http://steamcommunity.com/sharedfiles/filedetails/?id=834418950

If you do get in contact with the devs and get the code under a free license, consider offering your changes to boss animations and trap/doors opening immediately to that dev.

**Comment by Zamiell** [comment]
1) This mod is abandoned. Please post future issues for the [Racing+ mod](https://github.com/Zamiell/isaac-racing-client).
2) I've already known how to disable giantbook animations for years. Its a super simple one file fix. Every giantbook animation in the game uses the same file, which means that you can't mod out Betrayal animations without getting rid of black heart animations. I can't remove black heart animations for balance reasons. Other animations can be removed on a case by case basis. For example, currently there is a custom version of Betrayal that has no animation. As for other animations, feel free to propose removals in the Discord server for Racing+ and I will look into it.
